install:
  - wget https://github.com/libuv/libuv/archive/v0.10.36.tar.gz
  - tar -xzvf v0.10.36.tar.gz
  - cd v0.10.36 && ./configure --prefix=/usr && make && make install
before_install:
  - sudo apt-get install -y cmake
language: c
compiler:
  - gcc
script: cmake . && make